# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hw1_5ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.5
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from Q5 import *

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(368, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 351, 551))
        self.groupBox.setObjectName("groupBox")
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setGeometry(QtCore.QRect(20, 20, 321, 51))
        self.pushButton.setStyleSheet("font: 16pt \"Agency FB\";\n"
"font: 18pt \"Consolas\";")
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(show_trainimage)

        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_2.setGeometry(QtCore.QRect(20, 80, 321, 51))
        self.pushButton_2.setStyleSheet("font: 18pt \"Consolas\";")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.clicked.connect(show_hyperparameter)

        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_3.setGeometry(QtCore.QRect(20, 140, 321, 51))
        self.pushButton_3.setStyleSheet("font: 18pt \"Consolas\";")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_3.clicked.connect(show_model)

        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_4.setGeometry(QtCore.QRect(20, 200, 321, 51))
        self.pushButton_4.setStyleSheet("font: 18pt \"Consolas\";")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_4.clicked.connect(show_acc_loss)

        self.spinBox = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox.setGeometry(QtCore.QRect(20, 270, 321, 71))
        self.spinBox.setStyleSheet("font: 20pt \"Agency FB\";\n"
"font: 26pt \"Agency FB\";")
        self.spinBox.setObjectName("spinBox")
        self.pushButton_5 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_5.setGeometry(QtCore.QRect(20, 360, 311, 51))
        self.pushButton_5.setStyleSheet("font: 18pt \"Consolas\";")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_5.clicked.connect(lambda: test_image(self.spinBox.value()))

        self.pushButton_6 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_6.setGeometry(QtCore.QRect(20, 420, 311, 51))
        self.pushButton_6.setStyleSheet("font: 18pt \"Consolas\";")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_6.clicked.connect(train)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 368, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "VGG16 TEST"))
        self.pushButton.setText(_translate("MainWindow", "1. Show Train Images"))
        self.pushButton_2.setText(_translate("MainWindow", "2. Show HyperParameter "))
        self.pushButton_3.setText(_translate("MainWindow", "2. Show Model Shortcut "))
        self.pushButton_4.setText(_translate("MainWindow", "4.Show Accuracy"))
        self.pushButton_5.setText(_translate("MainWindow", "5.Test"))
        self.pushButton_6.setText(_translate("MainWindow", "6.Train"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
