# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.15.5
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from Q1 import *
from Q2 import *
from Q3 import *
from Q4 import *

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(905, 541)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 10, 231, 451))
        self.groupBox.setObjectName("groupBox")

        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setGeometry(QtCore.QRect(30, 30, 131, 31))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(findCorners)

        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_2.setGeometry(QtCore.QRect(30, 100, 131, 31))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.clicked.connect(find_instrinsic)

        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 150, 201, 131))
        self.groupBox_2.setObjectName("groupBox_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_3.setGeometry(QtCore.QRect(30, 70, 111, 41))
        self.pushButton_3.setObjectName("pushButton_3")

        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setGeometry(QtCore.QRect(10, 26, 61, 31))
        self.label.setObjectName("label")
        self.SelectImage = QtWidgets.QSpinBox(self.groupBox_2)
        self.SelectImage.setGeometry(QtCore.QRect(80, 30, 81, 22))
        self.SelectImage.setMinimum(1)
        self.SelectImage.setMaximum(15)
        self.SelectImage.setObjectName("SelectImage")
        self.pushButton_3.clicked.connect(lambda: find_extrinsic(self.SelectImage.value()))

        self.pushButton_10 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_10.setGeometry(QtCore.QRect(30, 310, 131, 31))
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_10.clicked.connect(find_distorsion)

        self.pushButton_11 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_11.setGeometry(QtCore.QRect(30, 370, 131, 31))
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_11.clicked.connect(Show_Result)

        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(270, 20, 181, 361))
        self.groupBox_3.setObjectName("groupBox_3")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_2.setGeometry(QtCore.QRect(12, 40, 151, 31))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_4.setGeometry(QtCore.QRect(10, 120, 151, 51))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_4.clicked.connect(lambda: augmented_reality(self.lineEdit_2.text()))
 
        self.pushButton_5 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_5.setGeometry(QtCore.QRect(10, 210, 151, 51))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_5.clicked.connect(lambda: show_vertical(self.lineEdit_2.text()))

        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(470, 20, 171, 361))
        self.groupBox_4.setObjectName("groupBox_4")
        self.pushButton_6 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_6.setGeometry(QtCore.QRect(10, 60, 151, 51))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_6.clicked.connect(stereo)
        self.pushButton_12 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_12.setGeometry(QtCore.QRect(10, 180, 151, 51))
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_12.clicked.connect(get_points)

        self.groupBox_5 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_5.setGeometry(QtCore.QRect(660, 20, 191, 361))
        self.groupBox_5.setObjectName("groupBox_5")
        self.pushButton_7 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_7.setGeometry(QtCore.QRect(20, 30, 151, 51))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_7.clicked.connect(createKeyPoint)
        self.pushButton_8 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_8.setGeometry(QtCore.QRect(20, 150, 151, 51))
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_8.clicked.connect(matchedKeyPoint)

        self.pushButton_9 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_9.setGeometry(QtCore.QRect(20, 250, 151, 51))
        self.pushButton_9.setObjectName("pushButton_9")

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 905, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "1. Calibration"))
        self.pushButton.setText(_translate("MainWindow", "1.1Find Corners"))
        self.pushButton_2.setText(_translate("MainWindow", "1.2 Find Intrinsic"))
        self.groupBox_2.setTitle(_translate("MainWindow", "1.3 Find Extrinsic"))
        self.pushButton_3.setText(_translate("MainWindow", "1.3 Find Extrinsic"))
        self.label.setText(_translate("MainWindow", "Select image"))
        self.pushButton_10.setText(_translate("MainWindow", "1.4 Find Distortion"))
        self.pushButton_11.setText(_translate("MainWindow", "1.5 Show Result"))
        self.groupBox_3.setTitle(_translate("MainWindow", "2. Augmented Reality"))
        self.pushButton_4.setText(_translate("MainWindow", "2.1 Show words on board"))
        self.pushButton_5.setText(_translate("MainWindow", "2.2 Show words vertically"))
        self.groupBox_4.setTitle(_translate("MainWindow", "3. Stereo Disparity Map"))
        self.pushButton_6.setText(_translate("MainWindow", "3.1 Strereo Disparity Map"))
        self.pushButton_12.setText(_translate("MainWindow", "3.2 Draw Point"))
        self.groupBox_5.setTitle(_translate("MainWindow", "4. SIFT"))
        self.pushButton_7.setText(_translate("MainWindow", "4.1 Keypoints"))
        self.pushButton_8.setText(_translate("MainWindow", "4.2 Matched keypoints"))
        self.pushButton_9.setText(_translate("MainWindow", "4.3 Wrap Image"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
